// Alert Rules Engine — data-driven rule definitions
// Each rule has: id, name, severity, source, category, condition (description), message (template)

export type AlertCategory =
  | "standard"
  | "discovery"
  | "infrastructure"
  | "llm"
  | "security"
  | "self-healing";

export type AlertSeverity = "info" | "warning" | "error" | "critical";

export interface AlertRule {
  id: string;
  name: string;
  severity: AlertSeverity;
  source: string;
  category: AlertCategory;
  condition: string;
  message: string;
}

export const alertRules: AlertRule[] = [
  // ============================================================
  // STANDARD (10)
  // ============================================================
  {
    id: "std-high-error-rate",
    name: "High Error Rate",
    severity: "error",
    source: "events",
    category: "standard",
    condition: "Error events exceed 20% of total events in last hour",
    message: "High error rate detected: error events exceed 20% of recent activity",
  },
  {
    id: "std-long-session",
    name: "Long Session Duration",
    severity: "warning",
    source: "sessions",
    category: "standard",
    condition: "Active session running longer than 2 hours",
    message: "Active session has been running for over 2 hours — possible hung process",
  },
  {
    id: "std-tool-failures",
    name: "Many Tool Failures",
    severity: "warning",
    source: "events",
    category: "standard",
    condition: "More than 10 tool failure events in last 30 minutes",
    message: "Excessive tool failures detected in the last 30 minutes",
  },
  {
    id: "std-event-backlog",
    name: "Event Backlog",
    severity: "warning",
    source: "events",
    category: "standard",
    condition: "More than 500 unprocessed events in queue",
    message: "Event backlog growing: large number of events queued",
  },
  {
    id: "std-stale-sessions",
    name: "Stale Sessions",
    severity: "info",
    source: "sessions",
    category: "standard",
    condition: "Active session with no events for 30+ minutes",
    message: "Stale session detected — active but idle for 30+ minutes",
  },
  {
    id: "std-agent-crash-loop",
    name: "Agent Crash Loop",
    severity: "critical",
    source: "agents",
    category: "standard",
    condition: "Agent failed and restarted 3+ times in 10 minutes",
    message: "Agent crash loop detected: multiple restarts in short period",
  },
  {
    id: "std-high-event-count",
    name: "High Event Count",
    severity: "warning",
    source: "events",
    category: "standard",
    condition: "More than 1000 events in a single session",
    message: "Unusually high event volume in session",
  },
  {
    id: "std-context-overflow",
    name: "Context Overflow",
    severity: "error",
    source: "contextSnapshots",
    category: "standard",
    condition: "Context tokens exceed 180k",
    message: "Context overflow risk: token count exceeds 180k threshold",
  },
  {
    id: "std-file-op-failures",
    name: "File Operation Failures",
    severity: "warning",
    source: "fileOps",
    category: "standard",
    condition: "Multiple file operation failures in last 15 minutes",
    message: "File operation failures detected in the last 15 minutes",
  },
  {
    id: "std-hook-failures",
    name: "Hook Failures",
    severity: "warning",
    source: "events",
    category: "standard",
    condition: "Hook execution failures detected in last 30 minutes",
    message: "Hook execution failures detected in the last 30 minutes",
  },

  // ============================================================
  // DISCOVERY (10)
  // ============================================================
  {
    id: "disc-mcp-disconnected",
    name: "MCP Server Disconnected",
    severity: "error",
    source: "mcpServers",
    category: "discovery",
    condition: "MCP server status is disconnected or error",
    message: "MCP server is disconnected or in error state",
  },
  {
    id: "disc-tool-usage-dropped",
    name: "Tool Usage Dropped",
    severity: "info",
    source: "discoveredTools",
    category: "discovery",
    condition: "Previously active tool not used in 24+ hours",
    message: "Tool usage has dropped — previously active tool not used recently",
  },
  {
    id: "disc-unknown-tool",
    name: "Unknown Tool Detected",
    severity: "warning",
    source: "discoveredTools",
    category: "discovery",
    condition: "Tool discovered from unknown source",
    message: "Unknown tool detected from an unrecognized source",
  },
  {
    id: "disc-plugin-disabled",
    name: "Plugin Disabled",
    severity: "info",
    source: "plugins",
    category: "discovery",
    condition: "A previously enabled plugin has been disabled",
    message: "Plugin has been disabled",
  },
  {
    id: "disc-stale-config",
    name: "Stale Configuration",
    severity: "info",
    source: "agentConfigs",
    category: "discovery",
    condition: "Configuration not updated in 7+ days",
    message: "Configuration has not been updated in over 7 days",
  },
  {
    id: "disc-config-drift",
    name: "Config Drift Detected",
    severity: "warning",
    source: "configChanges",
    category: "discovery",
    condition: "Multiple rapid config changes detected",
    message: "Config drift: multiple rapid changes detected in the last hour",
  },
  {
    id: "disc-missing-hooks",
    name: "Missing Hooks",
    severity: "info",
    source: "registeredHooks",
    category: "discovery",
    condition: "No hooks registered for critical hook types",
    message: "No hooks registered — consider adding PreToolUse or PostToolUse hooks",
  },
  {
    id: "disc-skill-not-found",
    name: "Skill Not Found",
    severity: "warning",
    source: "skills",
    category: "discovery",
    condition: "Referenced skill is not in the skills registry",
    message: "Referenced skill was not found in the registry",
  },
  {
    id: "disc-too-many-tools",
    name: "Too Many Tools",
    severity: "warning",
    source: "discoveredTools",
    category: "discovery",
    condition: "More than 100 tools discovered — potential performance impact",
    message: "Tool sprawl: over 100 tools discovered — consider pruning unused tools",
  },
  {
    id: "disc-server-timeout",
    name: "MCP Server Timeout",
    severity: "error",
    source: "mcpServers",
    category: "discovery",
    condition: "MCP server not seen in 5+ minutes",
    message: "MCP server has not responded in over 5 minutes",
  },

  // ============================================================
  // INFRASTRUCTURE (10)
  // ============================================================
  {
    id: "infra-container-stopped",
    name: "Docker Container Stopped",
    severity: "error",
    source: "dockerContainers",
    category: "infrastructure",
    condition: "Container status is stopped or error",
    message: "Docker container is stopped or in error state",
  },
  {
    id: "infra-high-cpu",
    name: "Docker High CPU",
    severity: "warning",
    source: "dockerContainers",
    category: "infrastructure",
    condition: "Container CPU usage exceeds 80%",
    message: "Docker container CPU usage exceeds 80%",
  },
  {
    id: "infra-high-memory",
    name: "Docker High Memory",
    severity: "warning",
    source: "dockerContainers",
    category: "infrastructure",
    condition: "Container memory exceeds 1024 MB",
    message: "Docker container memory usage exceeds 1024 MB",
  },
  {
    id: "infra-supabase-degraded",
    name: "Supabase Service Degraded",
    severity: "warning",
    source: "supabaseHealth",
    category: "infrastructure",
    condition: "Supabase service health is degraded",
    message: "Supabase service is degraded",
  },
  {
    id: "infra-supabase-down",
    name: "Supabase Service Down",
    severity: "critical",
    source: "supabaseHealth",
    category: "infrastructure",
    condition: "Supabase service health is down",
    message: "Supabase service is DOWN",
  },
  {
    id: "infra-high-response-time",
    name: "High Response Time",
    severity: "warning",
    source: "supabaseHealth",
    category: "infrastructure",
    condition: "Service response time exceeds 2000ms",
    message: "Service response time exceeds 2000ms threshold",
  },
  {
    id: "infra-disk-space-low",
    name: "Disk Space Low",
    severity: "error",
    source: "metricSnapshots",
    category: "infrastructure",
    condition: "Disk usage metric exceeds 90%",
    message: "Disk space critically low: usage exceeds 90%",
  },
  {
    id: "infra-container-restart-loop",
    name: "Container Restart Loop",
    severity: "critical",
    source: "dockerContainers",
    category: "infrastructure",
    condition: "Container restarted 3+ times in 10 minutes",
    message: "Docker container is in a restart loop",
  },
  {
    id: "infra-image-outdated",
    name: "Container Image Outdated",
    severity: "info",
    source: "dockerContainers",
    category: "infrastructure",
    condition: "Container image not updated in 30+ days",
    message: "Docker container image may be outdated",
  },
  {
    id: "infra-network-error",
    name: "Network Error",
    severity: "error",
    source: "supabaseHealth",
    category: "infrastructure",
    condition: "Multiple consecutive health check failures",
    message: "Network connectivity issues detected for service",
  },

  // ============================================================
  // LLM (10)
  // ============================================================
  {
    id: "llm-high-cost",
    name: "High Cost Threshold",
    severity: "warning",
    source: "llmMetrics",
    category: "llm",
    condition: "Total LLM cost exceeds $5 in last hour",
    message: "LLM spending alert: cost exceeds $5 in the last hour",
  },
  {
    id: "llm-rate-limit",
    name: "Rate Limit Approaching",
    severity: "warning",
    source: "llmMetrics",
    category: "llm",
    condition: "More than 50 LLM calls in 5 minutes",
    message: "Rate limit risk: too many LLM calls in the last 5 minutes",
  },
  {
    id: "llm-provider-errors",
    name: "Provider Error Spike",
    severity: "error",
    source: "llmMetrics",
    category: "llm",
    condition: "LLM provider returning errors",
    message: "LLM provider error rate spiking",
  },
  {
    id: "llm-high-latency",
    name: "High Latency",
    severity: "warning",
    source: "llmMetrics",
    category: "llm",
    condition: "Average LLM latency exceeds 10 seconds",
    message: "LLM latency high: average exceeds 10 seconds",
  },
  {
    id: "llm-token-budget",
    name: "Token Budget Exceeded",
    severity: "error",
    source: "llmMetrics",
    category: "llm",
    condition: "Total token usage exceeds 1M tokens in a session",
    message: "Token budget exceeded: over 1M tokens used in session",
  },
  {
    id: "llm-model-deprecated",
    name: "Model Deprecated",
    severity: "info",
    source: "llmMetrics",
    category: "llm",
    condition: "Using a model flagged as deprecated",
    message: "Deprecated model in use — consider migrating to a newer model",
  },
  {
    id: "llm-cost-anomaly",
    name: "Cost Anomaly",
    severity: "warning",
    source: "llmMetrics",
    category: "llm",
    condition: "Single LLM call cost exceeds $0.50",
    message: "Cost anomaly: single LLM call unusually expensive",
  },
  {
    id: "llm-many-retries",
    name: "Many Retries",
    severity: "warning",
    source: "llmMetrics",
    category: "llm",
    condition: "More than 5 retries for a single LLM call",
    message: "Excessive LLM retries detected",
  },
  {
    id: "llm-all-providers-down",
    name: "All Providers Down",
    severity: "critical",
    source: "llmMetrics",
    category: "llm",
    condition: "No successful LLM calls in last 5 minutes",
    message: "All LLM providers appear to be down — no successful calls in 5 minutes",
  },
  {
    id: "llm-quota-exhausted",
    name: "Quota Exhausted",
    severity: "critical",
    source: "llmMetrics",
    category: "llm",
    condition: "LLM usage quota fully exhausted",
    message: "LLM quota exhausted — requests will be rejected",
  },

  // ============================================================
  // SECURITY (12)
  // ============================================================
  {
    id: "sec-critical-event",
    name: "Critical Security Event",
    severity: "critical",
    source: "securityEvents",
    category: "security",
    condition: "Security event with critical severity detected",
    message: "Critical security event detected",
  },
  {
    id: "sec-many-high-severity",
    name: "Many High-Severity Events",
    severity: "error",
    source: "securityEvents",
    category: "security",
    condition: "More than 5 high-severity security events in 1 hour",
    message: "Multiple high-severity security events in the last hour",
  },
  {
    id: "sec-unmitigated",
    name: "Unmitigated Security Event",
    severity: "error",
    source: "securityEvents",
    category: "security",
    condition: "Security event remains unmitigated for 30+ minutes",
    message: "Unmitigated security event — open for over 30 minutes",
  },
  {
    id: "sec-permission-violation",
    name: "Permission Violation",
    severity: "error",
    source: "securityEvents",
    category: "security",
    condition: "Permission violation security event detected",
    message: "Permission violation detected",
  },
  {
    id: "sec-rls-bypass",
    name: "RLS Bypass Attempt",
    severity: "critical",
    source: "securityEvents",
    category: "security",
    condition: "RLS bypass attempt detected",
    message: "RLS bypass attempt detected",
  },
  {
    id: "sec-suspicious-tool",
    name: "Suspicious Tool Pattern",
    severity: "warning",
    source: "securityEvents",
    category: "security",
    condition: "Suspicious tool usage pattern flagged",
    message: "Suspicious tool usage pattern detected",
  },
  {
    id: "sec-injection-attempt",
    name: "Injection Attempt",
    severity: "critical",
    source: "securityEvents",
    category: "security",
    condition: "Potential injection attempt detected",
    message: "Injection attempt detected",
  },
  {
    id: "sec-high-frequency",
    name: "High Event Frequency",
    severity: "warning",
    source: "securityEvents",
    category: "security",
    condition: "More than 20 security events in 10 minutes",
    message: "High security event frequency in the last 10 minutes",
  },
  {
    id: "sec-stale-mitigation",
    name: "Stale Mitigation",
    severity: "warning",
    source: "securityEvents",
    category: "security",
    condition: "Mitigation applied but event still recurring",
    message: "Stale mitigation — security event is recurring despite mitigation",
  },
  {
    id: "sec-new-attack-vector",
    name: "New Attack Vector",
    severity: "error",
    source: "securityEvents",
    category: "security",
    condition: "Previously unseen security event type detected",
    message: "New attack vector detected — previously unseen event type",
  },
  {
    id: "sec-privilege-escalation",
    name: "Privilege Escalation",
    severity: "critical",
    source: "securityEvents",
    category: "security",
    condition: "Privilege escalation attempt detected",
    message: "Privilege escalation attempt detected",
  },
  {
    id: "sec-auth-failure",
    name: "Auth Failure Spike",
    severity: "warning",
    source: "securityEvents",
    category: "security",
    condition: "Multiple authentication failures in short period",
    message: "Authentication failure spike in the last 10 minutes",
  },

  // ============================================================
  // SELF-HEALING (13)
  // ============================================================
  {
    id: "sh-component-failure",
    name: "Component Failure",
    severity: "error",
    source: "selfHealingEvents",
    category: "self-healing",
    condition: "Self-healing event with failed outcome",
    message: "Component failure detected via self-healing system",
  },
  {
    id: "sh-recovery-failed",
    name: "Recovery Failed",
    severity: "critical",
    source: "selfHealingEvents",
    category: "self-healing",
    condition: "Self-healing recovery action failed",
    message: "Recovery action failed — issue not resolved",
  },
  {
    id: "sh-escalation-triggered",
    name: "Escalation Triggered",
    severity: "warning",
    source: "selfHealingEvents",
    category: "self-healing",
    condition: "Self-healing escalated to human intervention",
    message: "Self-healing escalation triggered — human intervention requested",
  },
  {
    id: "sh-too-many-retries",
    name: "Too Many Retries",
    severity: "warning",
    source: "selfHealingEvents",
    category: "self-healing",
    condition: "More than 5 retry actions for same component in 1 hour",
    message: "Excessive self-healing retries for component in the last hour",
  },
  {
    id: "sh-version-rollback",
    name: "Version Rollback",
    severity: "warning",
    source: "selfHealingEvents",
    category: "self-healing",
    condition: "Rollback action detected",
    message: "Version rollback executed by self-healing system",
  },
  {
    id: "sh-pending-too-long",
    name: "Pending Too Long",
    severity: "warning",
    source: "selfHealingEvents",
    category: "self-healing",
    condition: "Self-healing event pending for 15+ minutes",
    message: "Self-healing action pending for over 15 minutes",
  },
  {
    id: "sh-cascading-failure",
    name: "Cascading Failure",
    severity: "critical",
    source: "selfHealingEvents",
    category: "self-healing",
    condition: "3+ different components failing within 5 minutes",
    message: "Cascading failure detected: multiple components affected",
  },
  {
    id: "sh-health-check-timeout",
    name: "Health Check Timeout",
    severity: "error",
    source: "selfHealingEvents",
    category: "self-healing",
    condition: "Health check for component timed out",
    message: "Health check timeout for component",
  },
  {
    id: "sh-multiple-components-down",
    name: "Multiple Components Down",
    severity: "critical",
    source: "selfHealingEvents",
    category: "self-healing",
    condition: "2+ components with failed status simultaneously",
    message: "Multiple components down simultaneously",
  },
  {
    id: "sh-recovery-loop",
    name: "Recovery Loop",
    severity: "error",
    source: "selfHealingEvents",
    category: "self-healing",
    condition: "Component alternating between resolved and failed",
    message: "Recovery loop detected: component oscillating between resolved and failed",
  },
  {
    id: "sh-version-conflict",
    name: "Version Conflict",
    severity: "warning",
    source: "versionHistory",
    category: "self-healing",
    condition: "Multiple version changes for same component in short period",
    message: "Version conflict: multiple version changes for component recently",
  },
  {
    id: "sh-action-timeout",
    name: "Action Timeout",
    severity: "error",
    source: "selfHealingEvents",
    category: "self-healing",
    condition: "Self-healing action has been running for 10+ minutes without resolution",
    message: "Self-healing action timeout — running for over 10 minutes without resolution",
  },
  {
    id: "sh-manual-intervention",
    name: "Manual Intervention Needed",
    severity: "critical",
    source: "selfHealingEvents",
    category: "self-healing",
    condition: "All automated recovery options exhausted",
    message: "Manual intervention required: all automated recovery options exhausted",
  },
];
